# Use the official Python image.
# https://hub.docker.com/_/python
FROM python:3.10-slim

# Set the working directory.
WORKDIR /app

# Install dependencies.
COPY requirements.txt requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

# RUN pip install pytest pytest-cov

# Copy the rest of the application code.
COPY . .

# Expose the port the app runs on. PORT is from the .env file.
EXPOSE ${PORT}

# Set environment variables.
ENV FLASK_APP=app.py
ENV FLASK_RUN_HOST=0.0.0.0

# Run tests
# CMD ["pytest", "--cov=app"]

# Run the application.
CMD ["flask", "run", "--host=0.0.0.0", "--port=${PORT}"]
